version: "3.6"

services:
    backend:
        container_name: backend
        build: ./
        command: npm start

        environment: 
            MONGO_HOST: mongodb://mongo:27017/rutes

        working_dir: /usr/src/doblevia-backend
        ports: 
            - "3001:3001" 
        volumes: 
            - ./:/usr/src/doblevia-backend
            - /usr/src/doblevia-backend/node_modules

    database:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"